### ISSUE TITLE
Proposals

### ISSUE THREAD

**Issue by dzarda** [rubberduck203/switch-hal#2]
Kudos for this.

1. `Activeness` could be called `Polarity`,  `ActiveState` or `ActiveLevel` to better match industry naming
2. Consider renaming the methods to something like `set_on()` or `turn_on()` to better match embedded-hal/Rust naming
3. Consider constructing via `.into_active_high()` and `.into_active_low()` (should be doable, I don't Rust well enough to swear by it tho)

**Comment by rubberduck203** [comment]
1. That's the word I was looking for! I created #4 to track it.
2. Seems kind of bike-sheddy. `on()` is a command, `set` adds no value to the name IMO, but what color should we paint that bike shed anyway? If this makes it's way into an `embedded-hal` PR, we can deal with it then.
3. Can you explain more please? I'm not sure what you would like to achieve with those functions. Do you want them added to the struct impl or the trait? For what purpose? Internal pull up/downs?

**Comment by dzarda** [comment]
3. This would would allow a more fluent construction in conjunction with hal impls:

```rs
let sw = gpiob.pb4
  .into_push_pull_output()
  .into_active_high();
```

**Comment by rubberduck203** [comment]
I see what you’re getting at now. 
Something like this?

```
trait IntoOutputSwitch {
    fn into_active_high(self) -> OutputSwitch;
}
```

Let’s open a dedicated issue for that.

**Comment by rubberduck203** [comment]
@dzarda I'm going to close this in preference of the more specific issues.
Thank you very much for the feedback.
